name: 'Python setup steps that can be reused'
description: 'Install dependencies, poetry, requirements'
inputs:
  python-version:
    required: true
    description: The python version

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends python3-dev

    - name: Install poetry
      shell: bash
      run: |
        PIP_BREAK_SYSTEM_PACKAGES=1 pip install poetry --user

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Install requirements
      shell: bash
      run: |
        PIP_BREAK_SYSTEM_PACKAGES=1 poetry install --no-interaction --no-root
